apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-flask-hello-am0z
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-flask-hello-am0z
    app.kubernetes.io/part-of: python-flask-hello
  name: python-flask-hello-am0z
  namespace: samburrai-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-flask-hello-am0z
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-flask-hello-am0z
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:E1KJk-python-flask-hello-am0z
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
