apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-flask-hello-am0z
  namespace: samburrai-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:35ff360450aa0649cfd15c44ae5ea5db272ea0d3251ed69623c97debdf3e402a
        name: my-python
        resources: {}
status: {}
